package com.mpowered.rules.consent_workflow;

import java.time.Duration;
import java.time.Instant;
import java.util.Date;

import com.mpowered.commons.pojo.userpojo.MinorUserPojo;

function boolean nonMinor(Date birthDate) {
    return Duration.between(Instant.ofEpochMilli(birthDate.getTime()), Instant.now()).toDays() > 4745;
}

rule "is_minor.minor"
when 
    $minor: MinorUserPojo( consentRequired == false )
    eval(nonMinor($minor.getBirthDate()))
then
    modify( $minor ) {
        setConsentRequired(true)
    }
end
